### PR TITLE
Pass constraints through options object

### PR DESCRIPTION
**Pull request by joshuacullenlux**

### CODE REVIEW

**Comment by nguyenchr** [comment]
might want to rename the parameter here as weell https://github.com/Tabcorp/strummer/blob/master/lib/factory.js#L9

not sure what to call it seeing as though the first parameter is also called opt hahaha

**Comment by deancouch** [comment]
Lets just update the README with the change

**Comment by joshuacullenlux** [comment]
@deancouch I've put updated the readme to have the object. 
https://github.com/Tabcorp/strummer/pull/107/files#diff-04c6e90faac2675aa89e2176d2eec7d8R263

Were you referring to something else?

**Comment by deancouch** [comment]
Ah, I completely missed it, thanks 👍

**Pull request merged**
